"""
System display functions

Contains
--------
- startup()
- login()
"""

from .helpers import clear, printc, print_lines
from .config import FancyLogin as FL, Logins, Load
from ..__init__ import __version__
from ..sql.models import Models

from time import sleep
from random import expovariate, uniform, choice



def sim_load() -> None:
    """
    Simulates loading for `startup()` bc it's cool

    Notes
    -----
    - Organic timing logic by ChatGPT
    """

    lines = [
        ('> Establishing encrypted tunnel to Deepwell Servers', 0.2, 0.5),
        ('> Syncing with Recordkeeping And Information Security Administration (RAISA)', 0.3, 0.7),
        ('> Validating cryptographic token', 0.8, 1.4),
        ('> SCiPNET interface launch sequence initiated', 0.4, 0.9)
    ]

    for line, min_t, max_t in lines:
        sleep(expovariate(Load.LOAD_RATE))
        printc(line, end='', flush=True)

        for _ in range(3):
            sleep(uniform(min_t, max_t))

            line = f'{line} .'
            print(f'\r{line:^{SIZE}}', end='', flush=True)

        # occasional hiccup for 'lag'
        if uniform(0, 1) < Load.HICCUP_PROBABILITY:
            sleep(uniform(*Load.HICCUP_DELAY))

    sleep(0.25)
    print('\n')


def startup() -> None:
    """
    Prints a fancy startup screen

    Notes
    -----
    - Ascii art generated by ChatGPT
    - Text from `patorjk.com/software/taag/` Font: ANSI Shadow
    """
    clear()

    # main terminal screen
    print_lines([
        '',
        '███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀▀▀▀███▀',
        '███████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓███████',
        '██ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ░░ ██',
        '',
        '███████╗ ██████╗██████╗     ███████╗ ██████╗ ██╗   ██╗███╗   ██╗██████╗  █████╗ ████████╗██╗ ██████╗ ███╗   ██╗',
        '██╔════╝██╔════╝██╔══██╗    ██╔════╝██╔═══██╗██║   ██║████╗  ██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║',
        '███████╗██║     ██████╔╝    █████╗  ██║   ██║██║   ██║██╔██╗ ██║██║  ██║███████║   ██║   ██║██║   ██║██╔██╗ ██║',
        '╚════██║██║     ██╔═══╝     ██╔══╝  ██║   ██║██║   ██║██║╚██╗██║██║  ██║██╔══██║   ██║   ██║██║   ██║██║╚██╗██║',
        '███████║╚██████╗██║         ██║     ╚██████╔╝╚██████╔╝██║ ╚████║██████╔╝██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║',
        '╚══════╝ ╚═════╝╚═╝         ╚═╝      ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝',
        'Secure | Contain | Protect',
        '',
        f'— [ ACCESS PORTAL: SCiPNET TERMINAL v{__version__} ] —',
        '██ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ░░ ██',
        '███████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓███████',
        '███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄▄▄▄███▄',
        '',
        ''
    ])

    # simulate loading (bc it's cool)
    sim_load()
    print_lines([
                 'SCP Foundation CoreNode Connection: STABLE',
                 '',
                 '[The Foundation database is CLASSIFIED]',
                 '[Unauthorized access will result in detainment]',
                 ''
               ])


def _f_line(line: str) -> str:
        """Helper to format a line for `_gen_login_lines()`"""
        return f'{FL.L_R}{line:^FL.CONTENT_WIDTH}{FL.L_R}'

def _gen_login_lines(title: str, name: str) -> list[str]:
    """
    Generates lines to print based on user title
    """

    # validate title
    if title not in SPECIAL_TITLES:
        raise ValueError(f'got invalid title: {title}, '
                         f'expected title to be in {SPECIAL_TITLES}')

    Parameters
    ----------
    title : str
        user's title
    name : str
        user's name

    Returns
    -------
    list[str]
        login message lines
    """

    # validation
    if title not in Logins.PROFILES.keys():
        valid_titles = [f'{t!r}' for t in Logins.PROFILES.keys()]

        raise ValueError(f'Invalid title: {title!r}, '
                          'expected one of: '
                          f'{", ".join(valid_titles)}')

    if not isinstance(name, str):
        raise TypeError(f'expected `name` to be type str,'
                        f' got {type(name).__name__}')
    elif not name or name.isspace():
        raise ValueError('name cannot be empty or whitespace')
    elif '{' in name or '}' in name:
        raise ValueError('name cannot contain "{" or "}"')

    # get profile
    prof = Logins.PROFILES[title]

    # generate & return lines
    return [
            '', FL.TB_LINE, FL.SEP,
            _f_line(f'<< {prof.Auth_Type} AUTHORIZATION VERIFIED >>'),
            FL.SEP,
            _f_line(f'CLEARANCE LEVEL: {prof.Clear_Type}'),
            FL.SEP,
            _f_line(prof.Welcome_Msg.format(name=name)),
            _f_line(prof.Logging_Msg),
            FL.SEP,
            _f_line(f'SYSTEM STATUS: {prof.Sys_Status_Msg}'),
            FL.SEP, FL.TB_LINE, ''
           ]

    return result

def login(usr: Models.User) -> None:
    """
    prints fancy login messages when
    a user logs in.

    Parameters
    ----------
    usr : Models.User
        user logging in

    Raises
    ------
    TypeError
        If `usr` is not a Models.User instance

    Notes
    -----
    Art by ChatGPT
    """

    # set lines depending on usr title
    if title == 'O5 Council Member':
        lines = [
            '',
            reused2,
            reused1,
            '////' + f'{'<< O5 AUTHORIZATION VERIFIED >>':^112}' + '////',
            reused1,
            '////' + f'{'CLEARANCE LEVEL: 6 - COSMIC TOP SECRET':^112}' + '////',
            reused1,
            '////' + f'{f'Welcome back, {usr.name}.':^112}' + '////',
            '////' + f'{f'This session is being logged by CoreNode Zero.':^112}' + '////',
            reused1,
            '////' + f'{'SYSTEM STATUS: OPERATIONAL | DEEPWELL CHANNEL ENCRYPTED':^112}' + '////',
            reused1,
            reused2,
            '',
        ]

    elif title == 'Site Director':
        lines = [
            '',
            reused2,
            reused1,
            '////' + f'{'<< DIRECTOR AUTHORIZATION VERIFIED >>':^112}' + '////',
            reused1,
            '////' + f'{'CLEARANCE LEVEL: 5 - TOP SECRET':^112}' + '////',
            reused1,
            '////' + f'{f'Welcome back, {usr.name}.':^112}' + '////',
            '////' + f'{'All actions are recorded and reviewed by O5 Liaison - Node Black':^112}' + '////',
            reused1,
            '////' + f'{'SYSTEM STATUS: OPERATIONAL | DEEPWELL CHANNEL ENCRYPTED':^112}' + '////',
            reused1,
            reused2,
            '',
        ]

    elif title == 'Administrator':
        lines = [
            '',
            reused2,
            reused1,
            '////' + f'{'<< ADMINISTRATOR AUTHORIZATION VERIFIED >>':^112}' + '////',
            reused1,
            '////' + f'{'CLEARANCE LEVEL: UNBOUNDED | OVERRIDE: UNIVERSAL | LOGGING: DISABLED':^112}' + '////',
            reused1,
            '////' + f'{'Welcome, Administrator. All systems stand by for your instruction.':^112}' + '////',
            '////' + f'{'There are no restrictions. There are no records.':^112}' + '////',
            reused1,
            '////' + f'{'SYSTEM STATUS: OPERATIONAL | DEEPWELL CHANNEL ENCRYPTED | ENCLAVE MODE ACTIVE':^112}' + '////',
            reused1,
            reused2,
            '',
        ]
    if usr.title.name in Logins.PROFILES.keys():
        lines = _gen_login_lines(usr.title.name, usr.name)

    else:
        lines = [
            '',
            f'Welcome back, {title} {usr.name}',
            f'(Clearance {usr.clearance_lvl.name})',
            '',
        ]

    print_lines(lines)



if __name__ == '__main__':
    print('Testing system display functions...\n\n')
    startup()

    test_user = Models.User(
        id=1,
        name='Jane Doe',
        title=Models.IDandName(id=2, name='Site Director'),
        clearance_lvl=Models.IDandName(id=5, name='Top Secret')
    )
    login(test_user)

    test_user.title = Models.IDandName(id=1, name='O5 Council Member')
    login(test_user)

    test_user.title = Models.IDandName(id=0, name='Administrator')
    login(test_user)
