"""
System display functions

Contains
--------
- startup()
- login()
"""

from typing import Literal

from .helpers import clear, printc, print_lines
from .core.boxes import fancy_box, fancy_box_with_text
from ..general.display_config import FancyLogin as FL, Logins, Load
from ..general.validation import validate_field, validate_str
from ..__init__ import __version__
from ..sql.transformers import Models

from time import sleep
from random import expovariate, uniform


def sim_load() -> None:
    """
    Simulates loading for `startup()` bc it's cool

    Notes
    -----
    - Organic timing logic by ChatGPT
    """

    lines = [
        ('> Establishing encrypted tunnel to Deepwell Servers', 0.2, 0.5),
        (f'> Syncing with {Load.RAISA} (RAISA)', 0.3, 0.7),
        ('> Validating cryptographic token', 0.8, 1.4),
        ('> SCiPNET interface launch sequence initiated', 0.4, 0.9)
    ]

    for line, min_t, max_t in lines:
        sleep(expovariate(Load.LOAD_RATE))
        printc(line, end='', flush=True)

        for i in range(1, 4): # three dots
            sleep(uniform(min_t, max_t))
            printc(f'{line}{" ." * i}', end='', flush=True, overwrite=True) # one char over 😭

        # occasional hiccup for 'lag'
        if uniform(0, 1) < Load.HICCUP_PROBABILITY:
            sleep(uniform(*Load.HICCUP_DELAY))

    sleep(0.25)
    print('\n') # extra newline after loading for spacing


def startup() -> None:
    """
    Prints a fancy startup screen

    Notes
    -----
    - Ascii art generated by ChatGPT
    - Text from `patorjk.com/software/taag/` Font: ANSI Shadow
    """
    clear()

    # main terminal screen (ignore line length)
    fancy_box([
        '███████╗ ██████╗██████╗     ███████╗ ██████╗ ██╗   ██╗███╗   ██╗██████╗  █████╗ ████████╗██╗ ██████╗ ███╗   ██╗',
        '██╔════╝██╔════╝██╔══██╗    ██╔════╝██╔═══██╗██║   ██║████╗  ██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║',
        '███████╗██║     ██████╔╝    █████╗  ██║   ██║██║   ██║██╔██╗ ██║██║  ██║███████║   ██║   ██║██║   ██║██╔██╗ ██║',
        '╚════██║██║     ██╔═══╝     ██╔══╝  ██║   ██║██║   ██║██║╚██╗██║██║  ██║██╔══██║   ██║   ██║██║   ██║██║╚██╗██║',
        '███████║╚██████╗██║         ██║     ╚██████╔╝╚██████╔╝██║ ╚████║██████╔╝██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║',
        '╚══════╝ ╚═════╝╚═╝         ╚═╝      ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝',
        'Secure | Contain | Protect',
        '',
        f'— [ ACCESS PORTAL: SCiPNET TERMINAL v{__version__} ] —'
    ])
    print()

    # simulate loading (bc it's cool)
    sim_load()
    sleep(0.5)
    print_lines([
                 'SCP Foundation CoreNode Connection: STABLE',
                 '',
                 '[The Foundation database is CLASSIFIED]',
                 '[Unauthorized access will result in detainment]',
                 ''
               ])


def _f_line(line: str) -> str:
        """Helper to format a line for `_gen_login_lines()`"""
        return f'{FL.L_R}{line:^{FL.CONTENT_WIDTH}}{FL.L_R}'

def _gen_login_lines(title: str, name: str) -> list[str]:
    """
    Generates lines to print based on user title

    Parameters
    ----------
    title : str
        user's title
    name : str
        user's name

    Returns
    -------
    list[str]
        login message lines
    """

    # validation
    if title not in Logins.PROFILES.keys():
        valid_titles = [f'{t!r}' for t in Logins.PROFILES.keys()]

        raise ValueError(f'Invalid title: {title!r}, '
                          'expected one of: '
                          f'{", ".join(valid_titles)}')

    validate_str('name', name)
    if '{' in name or '}' in name:
        raise ValueError('name cannot contain "{" or "}"')

    # get profile
    prof = Logins.PROFILES[title]

    # generate & return lines
    return [
            '', FL.TB_LINE, FL.SEP,
            _f_line(f'<< {prof.Auth_Type} AUTHORIZATION VERIFIED >>'),
            FL.SEP,
            _f_line(f'CLEARANCE LEVEL: {prof.Clear_Type}'),
            FL.SEP,
            _f_line(prof.Welcome_Msg.format(name=name)),
            _f_line(prof.Logging_Msg),
            FL.SEP,
            _f_line(f'SYSTEM STATUS: {prof.Sys_Status_Msg}'),
            FL.SEP, FL.TB_LINE, ''
           ]


def login(usr: Models.User) -> None:
    """
    prints fancy login messages when
    a user logs in.

    Parameters
    ----------
    usr : Models.User
        user logging in

    Raises
    ------
    TypeError
        If `usr` is not a Models.User instance

    Notes
    -----
    Art by ChatGPT
    """

    # validation
    validate_field('usr', usr, Models.User)
    # rest is handled by pydantic


    # set lines depending on usr title & name
    if usr.title.name in Logins.PROFILES.keys():
        lines = _gen_login_lines(usr.title.name, usr.name)
    else:
        lines = [
                 '',
                 f'Welcome back, {usr.title.name} {usr.name}',
                 f'(Clearance {usr.clearance_lvl.name})',
                 '',
                ]

    print_lines(lines)

def login_fail(field: Literal['user_id', 'password']) -> None:
    """
    prints a fancy login failure message

    Parameters
    ----------
    field : Literal['user_id', 'password']
        the field that caused the failure

    Raises
    ------
    ValueError
        If `field` is not in `['user_id', 'password']`

    Notes
    -----
    Art by ChatGPT
    """

    # validation
    if field not in ['user_id', 'password']:
        raise ValueError(f'Invalid field: {field!r}, '
                          "expected one of: 'user_id', 'password'")

    cred = 'IDENTIFICATION' if field == 'user_id' else 'AUTHENTICATION'
    fancy_box_with_text(
        [
         f'{cred} INVALID',
         '',
         'ACCESS DENIED',
         'SESSION TERMINATED'
        ],
        []
    )



if __name__ == '__main__':
    print('Testing system display functions...\n\n')
    startup()

    from datetime import datetime

    test_user = Models.User(
        id=1,
        name='Jane Doe',
        title=Models.IDandName(id=2, name='Site Director'),
        clearance_lvl=Models.IDandName(id=5, name='Top Secret'),
        site_id=1,
        created_at=datetime.now(), updated_at=datetime.now()
    )

    login(test_user)

    test_user.title = Models.IDandName(id=1, name='O5 Council Member')
    login(test_user)

    test_user.title = Models.IDandName(id=0, name='Administrator')
    login(test_user)
